## Data Analysis using Python
## Day 2

### 1. Reading Data with Pandas

#### 1. Reading CSV Files
The most straightforward way to read a CSV file is using the `pd.read_csv()` method.

**Key Parameters:**
* `filepath_or_buffer`: The path to the CSV file. It can be a local file path or a URL.
* `sep`: Specifies the delimiter. The default is a comma (`,`), but you can use other delimiters (e.g., `;`, `|`).
* `header`: Row number(s) to use as the column names. Default is 0 (first row).
* `names`: If column names are not present, you can pass a list of column names.
* `index_col`: Column(s) to set as the index of the DataFrame.

In [18]:
# import pandas

In [19]:
# read the file patient_data.csv

In [20]:
# read the file patient_data.csv with sep |

In [21]:
# read the file patient_data.csv with sep | and headers in row 1

In [22]:
names = ["MRN",	"Name",	"Age",	"Gender",	"Weight",	"Height",	"BMI"]

# read the file patient_data.csv and use the following names as headers

In [23]:
names = ["MRN",	"Name",	"Age",	"Gender",	"Weight",	"Height",	"BMI"]

# read the file patient_data.csv and use the following names as headers and the MRN as index

#### 2. Reading Excel Files
To read Excel files, use `pd.read_excel()`. This method supports multiple sheets, which is useful for more complex Excel files.

**Key Parameters:**
* `io`: Path to the Excel file.
* `sheet_name`: Specifies which sheet to read. Default is 0 (first sheet).
Can be an integer for sheet index, a string for sheet name, or a list of names/indices to load multiple sheets.
* `header`: Row number to use as the column names.
* `index_col`: Column(s) to set as the index of the DataFrame.
* `usecols`: Specify which columns to parse from the file.

In [24]:
# read the patient_data.xlsx file

In [25]:
# read the first page from the patient_data.xlsx file

In [26]:
# read the page Medical History from the patient_data.xlsx file

In [27]:
# read the page Medical History from the patient_data.xlsx file for columns "Patient ID", "Visit Date", "Medications"

### 2. Data Selection and Filtering

#### 1. Selecting Specific Columns
To select specific columns, we can use double brackets `[['column1', 'column2']]`.

In [28]:
# Load the appointments.xlsx Excel File

In [29]:
# show the first 5 rows

In [30]:
# show the first 10 rows

In [31]:
# show the last 5 rows

In [32]:
# Select only appointment_id, patient_id, and reason_for_visit.

#### 2. Filtering Rows Based on a Condition
We can filter rows by applying conditions directly on the DataFrame.

In [33]:
# Filter rows where copay amount is greater than 0.5

To filter using multiple conditions, use the & (and) or | (or) operators.

In [34]:
# Filter rows where insurance provider is 'Cigna' and copay is less than 0.5

#### 3. Using `.loc` and `.iloc` to Select Rows and Columns
* The `.loc` method allows you to select specific rows and columns by labels.
* The `.iloc` method allows you to select rows and columns by their index positions.

In [32]:
# Select appointments with ID 1, 2, and 3 and show only the 'reason_for_visit' and 'diagnosis'
select = ['reason_for_visit', 'diagnosis']
cond = appointments['appointment_id'].isin([1, 2, 3])

appointments.loc[cond, select]

,reason_for_visit,diagnosis
0,"Maecenas leo odio, condimentum id, luctus nec,...",Quisque porta volutpat erat. Quisque erat eros...
1,Aliquam quis turpis eget elit sodales sceleris...,Vivamus tortor. Duis mattis egestas metus.
2,Suspendisse ornare consequat lectus. In est ri...,Donec ut mauris eget massa tempor convallis. N...

In [34]:
# Select first 5 rows and columns by position
appointments.iloc[0:5, 0:5]

   appointment_id appointment_date appointment_time  patient_id doctor_id
0               1        1/19/2022          9:05 AM      227440       U47
1               2         9/2/2022          7:42 PM      224063       M57
2               3        6/11/2022          5:35 PM      228629       J53
3               4       11/12/2022          1:40 AM      225910       E54
4               5        9/21/2022          1:38 PM      228331       N24

#### 4. Filtering Data with `.query()`
The `.query()` method allows you to filter data using a more readable string-based syntax.

In [35]:
# Filter appointments where copay_amount is greater than 0.3 and insurance_provider is "Aetna".